%!Rnw weave = knitr
%!TEX program = pdflatex
\documentclass[11pt,english]{article}
\usepackage[T1]{fontenc}
\usepackage{XCharter} % crisper, more contemporary serif than Palatino
\usepackage{microtype}
\usepackage{needspace}
\usepackage[utf8]{inputenc}
\usepackage[a4paper]{geometry}
\geometry{verbose,tmargin=1in,bmargin=1in,lmargin=1in,rmargin=1in}
%\setlength{\parskip}{\smallskipamount} % removing this line helped problem with extra page breaks between sections
\setlength{\parindent}{0pt}
\usepackage{array}

\makeatletter

\providecommand{\tabularnewline}{\\}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% User specified LaTeX commands.
\makeatother
\usepackage{fancyhdr}
\usepackage{lastpage}
\pagestyle{fancy}
\usepackage[small,compact]{titlesec}
\titleformat{\section}{\color{cvaccent}\Large\bfseries}{}{0em}{}[{\color{cvaccent!60}\titlerule}]
\titlespacing*{\section}{0pt}{1.6ex}{1.0ex}
\titleformat{\subsection}{\color{cvaccent}\bfseries}{}{0em}{}
\titlespacing*{\subsection}{0pt}{1.2ex}{0.5ex}
\titleformat{\subsubsection}{\normalfont\bfseries\itshape}{}{0em}{}
\titlespacing*{\subsubsection}{0pt}{1.1ex}{0.4ex}
\usepackage[small,it]{caption}
\addtolength{\belowcaptionskip}{-3mm}
\addtolength{\abovecaptionskip}{-3mm}
\usepackage{hanging}
\usepackage{babel}
\usepackage[hidelinks]{hyperref}
\makeatletter
\g@addto@macro{\UrlBreaks}{\do\-}
\makeatother
\usepackage{xcolor}
\definecolor{cvaccent}{HTML}{1F5C57} % dark teal accent
\usepackage{tabularx}
\usepackage{xltabular} % tabularx-style columns that break automatically across pages
\setlength{\LTpre}{0pt}  % longtable/xltabular add ~12pt before/after each table
\setlength{\LTpost}{0pt} % by default; zero this out to avoid stacked gaps
% between consecutive short tables (e.g. Major grants -> Awards -> Small grants)
\newcommand\reverselabel[1]{%
  \def\theenumi{}%
  \renewcommand\makelabel{\makebox[\dimexpr\labelwidth-3pt\relax][r]{%
    \the\numexpr#1-\value{enumi}+1\relax}}}%

\makeatother

\fancyhead{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot{}
\lfoot{Sheth CV}
%\cfoot{CV}
\rfoot{\thepage\ of \pageref{LastPage}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}

<<setup, echo=FALSE, include=FALSE>>=
source("cv_helpers.R")
@

\begin {center}

%----------------------------------------------------------------------------------------
%	YOUR NAME AND ADDRESS(ES) SECTION
%----------------------------------------------------------------------------------------

{\huge Seema Nayan Sheth}\tabularnewline
\vspace{1em}

\begin{tabularx}{\textwidth}{@{}>{\raggedright}X >{\raggedleft}X@{}}
\texttt{ssheth3}@ncsu.edu & Department of Plant and Microbial Biology \tabularnewline
Phone: (919) 515-4168 & North Carolina State University \tabularnewline
\url{http://www.seemasheth.weebly.com} & Raleigh, NC 27695 \tabularnewline
\end{tabularx}
\end{center}

%----------------------------------------------------------------------------------------
%	PROFESSIONAL APPOINTMENTS
%----------------------------------------------------------------------------------------

%\vspace{0.5ex}
\vspace{-1.75ex}
\section*{PROFESSIONAL APPOINTMENTS}
\nopagebreak[4]
%\noindent\Large{\textbf{PROFESSIONAL APPOINTMENTS}} 

{\bf Associate Professor} \hfill {2024 - present} \newline
Department of Plant and Microbial Biology, North Carolina State University
\vspace{0.5ex}

{\bf Assistant Professor} \hfill {2018 - 2024} \newline
Department of Plant and Microbial Biology, North Carolina State University
\vspace{0.5ex}

{\bf National Science Foundation Postdoctoral Fellow} \hfill {2016 - 2017} \newline
Department of Integrative Biology, University of California, Berkeley \newline
Supporting scientists: Dr. David Ackerly and Dr. Bruce Baldwin
\vspace{0.5ex}

{\bf Postdoctoral Research Associate} \hfill {2014 - 2015} \newline
Department of Ecology, Evolution, and Behavior, University of Minnesota \newline
Advisor: Dr. Ruth Shaw
\vspace{0.5ex}

{\bf Research Scientist: Conservation, Ecology, and Evolution} \hfill {2006 - 2008} \newline
Center for Conservation and Sustainable Development, Missouri Botanical Garden

%----------------------------------------------------------------------------------------
%	EDUCATION
%----------------------------------------------------------------------------------------

\section*{EDUCATION}
\nopagebreak[4]
%\noindent\Large{\textbf{EDUCATION}} 

{\bf Ph.D., Ecology} \hfill {2008 - 2014} \newline
Colorado State University \newline
Advisor: Dr. Amy Angert
\vspace{0.5ex}

{\bf M.S., Biology (Ecology, Evolution, and Systematics)} \hfill {2003 - 2006} \newline
University of Missouri - St. Louis \newline
Advisor: Dr. Bette Loiselle
\vspace{0.5ex}

{\bf B.A., Environmental Sciences and Spanish (double major)} \hfill {1998 - 2002} \newline
Washington University in St. Louis


%----------------------------------------------------------------------------------------
%	RESEARCH INTERESTS
%----------------------------------------------------------------------------------------

\section*{RESEARCH INTERESTS}
\nopagebreak[4]

%Plant evolutionary, population, and community responses to climate change
evolutionary and population ecology; biogeography; plant community responses to climate change

%----------------------------------------------------------------------------------------
%	PUBLICATIONS
%----------------------------------------------------------------------------------------

\section*{PUBLICATIONS}
\nopagebreak[4]
%\noindent\Large{\textbf{PUBLICATIONS}} 

Undergraduate student\textsuperscript{u}; Graduate student\textsuperscript{g}; Postdoctoral associate\textsuperscript{p}; Research technician\textsuperscript{t} 

<<publications, echo=FALSE, results='asis'>>=
cat(format_publications("data/publications.csv"))
@


\subsection*{Manuscripts in review/revision} 

<<manuscripts-in-review, echo=FALSE, results='asis'>>=
cat(format_hangpara_list("data/manuscripts_in_review.csv"))
@


%----------------------------------------------------------------------------------------
%	GRANTS, FELLOWSHIPS, AND AWARDS
%----------------------------------------------------------------------------------------

%\vspace{1ex}
%\begin{flushleft}
\section*{GRANTS, FELLOWSHIPS, AND AWARDS}
\nopagebreak[4]
%\noindent\Large{\textbf{GRANTS, FELLOWSHIPS, AND AWARDS}} 
%\end{flushleft}

\subsection*{Major grants and fellowships}
\nopagebreak[4]

<<major-grants, echo=FALSE, results='asis'>>=
cat(format_entry_table("data/major_grants.csv"))
@

\subsection*{Awards}
\nopagebreak[4]
<<awards, echo=FALSE, results='asis'>>=
cat(format_entry_table("data/awards.csv"))
@

\subsection*{Small grants, fellowships, and honors}
\nopagebreak[4]
<<small-grants, echo=FALSE, results='asis'>>=
cat(format_entry_table("data/small_grants.csv"))
@


%----------------------------------------------------------------------------------------
%	ADD PAGE BREAK; MOVE MANUALLY IF NEEDED
%----------------------------------------------------------------------------------------
%\newpage

%----------------------------------------------------------------------------------------
%	PRESENTATIONS
%----------------------------------------------------------------------------------------
%\vspace{1.5ex}
%\begin{flushleft}

\section*{PRESENTATIONS}
\nopagebreak[4]

\subsection*{Invited symposia}
\nopagebreak[4]

%\end{flushleft}

<<invited-symposia, echo=FALSE, results='asis'>>=
cat(format_invited_symposia("data/invited_symposia.csv"))
@

%\begin{flushleft}
\subsection*{Invited seminars}
\nopagebreak[4]
%\end{flushleft}

<<invited-seminars, echo=FALSE, results='asis'>>=
cat(format_seminar_list("data/invited_seminars.csv"))
@


%\begin{flushleft}
\subsection*{Contributed conference presentations}
\nopagebreak[4]
%\end{flushleft}

<<contributed-presentations, echo=FALSE, results='asis'>>=
cat(format_contributed_presentations("data/contributed_presentations.csv"))
@

%----------------------------------------------------------------------------------------
%	TEACHING
%----------------------------------------------------------------------------------------
\section*{TEACHING}
\nopagebreak[4]

\subsection*{North Carolina State University}
Plant Ecology, PB450-001, solo instructor \hfill {2019 - present} 

\subsection*{Colorado State University}
Principles of Plant Biology Laboratory, teaching assistant \hfill {2008 - 2014} \newline
Plant Ecology, guest lecturer \hfill {2012 - 2013} \newline
Plant Ecology, teaching assistant \hfill {2011 - 2012} \newline
Biology of Organisms, guest lecturer \hfill {2009} \newline
Cache La Poudre Junior High School, NSF GK-12 fellow, LaPorte, CO \hfill {2008 - 2009}

\subsection*{Missouri Botanical Garden}
Neotropical Plant Families, guest lecturer for University of Michigan course \hfill {2008} \newline
Conservation Biology, guest lecturer for University of Missouri - St. Louis course \hfill {2008} 

\subsection*{University of Missouri - St. Louis}
McCluer High School, NSF GK-12 fellow, Florissant, MO \hfill {2005 - 2006} \newline
Organisms and the Environment Laboratory, guest lecturer \hfill {2005} 

\subsection*{AmeriCorps Partnership for Youth}
Woodward Elementary School, tutor and teaching assistant, St. Louis, MO \hfill {2002 - 2003}

%----------------------------------------------------------------------------------------
%	MENTORING
%----------------------------------------------------------------------------------------
%\vspace{1.5ex}
%\begin{flushleft}
\section*{MENTORING}
\nopagebreak[4]

\subsection*{North Carolina State University}

<<mentoring-ncsu, echo=FALSE, results='asis'>>=
cat(format_mentoring_ncsu("data/mentoring_ncsu.csv"))
@

\subsection*{University of California, Berkeley}
\hangindent=5ex Mentored 7th graders at King Middle School as part of Be a Scientist outreach program \hfill {2017} 

\subsection*{University of Minnesota}
Sam Weaver (NSF REU student from St. Olaf College)		 \hfill {2015} 

\subsection*{Colorado State University}
Amber Weimer (Honor's thesis undergraduate student)		 \hfill {2013 - 2014} \newline
Trained, mentored, and supervised 17 undergraduates \& recent college graduates		 \hfill {2009 - 2014} \newline
Biological Summer Undergraduate Research Experience program committee member \hfill {2012} 

%----------------------------------------------------------------------------------------
%	SERVICE
%----------------------------------------------------------------------------------------
%\begin{flushleft}
\section*{SERVICE}
\nopagebreak[4]
%\end{flushleft}
%\begin{flushleft}
\subsection*{University service}
Wellness committee, Dept. of Plant and Microbial Biology, NCSU \hfill{2024 - present}\newline
Department head search committee, Dept. of Plant and Microbial Biology, NCSU \hfill{2025 }\newline
Evolution faculty search committee, Dept. of Plant and Microbial Biology, NCSU \hfill{2024 - 2025 }\newline
College of Agricultural and Life Sciences Research Committee, NCSU \hfill{2024} \newline
Plant Biology graduate admissions committee, NCSU \hfill{2018 - 2024} \newline
College of Agricultural and Life Sciences greenhouse committee, NCSU \hfill{2019 - present}\newline
Ecology faculty search committee, Dept. of Plant and Microbial Biology, NCSU \hfill{2019 - 2020 }\newline
Biology faculty search committee, Colorado State University \hfill{2012 - 2013} 

\subsection*{Professional service}
\nopagebreak[4]
<<professional-service, echo=FALSE, results='asis'>>=
cat(format_entry_table("data/professional_service.csv"))
@

\subsection*{Other service}
\nopagebreak[4]
<<other-service, echo=FALSE, results='asis'>>=
cat(format_entry_table("data/other_service.csv"))
@
 
%----------------------------------------------------------------------------------------
%	ADD PAGE BREAK; MOVE MANUALLY IF NEEDED
%----------------------------------------------------------------------------------------
%\newpage

%----------------------------------------------------------------------------------------
%	WORKING GROUPS AND WORKSHOPS
%----------------------------------------------------------------------------------------
%\vspace{1.5ex}
%\begin{flushleft}
%\begin{samepage}
\section*{WORKING GROUPS AND WORKSHOPS} %\Needspace{2in}
\nopagebreak[4] %needspace moves section heading to previous page

<<working-groups, echo=FALSE, results='asis'>>=
cat(format_entry_table("data/working_groups.csv"))
@

%\end{flushleft}

%----------------------------------------------------------------------------------------
%	PROFESSIONAL AFFILIATIONS AND SOCIETIES
%----------------------------------------------------------------------------------------
%\vspace{1.5ex}
%\begin{flushleft}
%\vspace{-2ex}
\section*{PROFESSIONAL AFFILIATIONS AND SOCIETIES}
\nopagebreak[4]
%\vspace{-0.5ex}
%\end{flushleft}

\renewcommand{\arraystretch}{1.2}
<<professional-affiliations, echo=FALSE, results='asis'>>=
cat(format_plain_list("data/professional_affiliations.csv"))
@
\vfill
\begin{center}
\textit{last updated \today}
\end{center}
\end{document}