\documentclass[11pt,english]{article}
\usepackage[T1]{fontenc}
\usepackage{needspace}
\usepackage[latin9]{inputenc}
\usepackage[a4paper]{geometry}
\geometry{verbose,tmargin=1in,bmargin=1in,lmargin=1in,rmargin=1in}
%\setlength{\parskip}{\smallskipamount} % removing this line helped problem with extra page breaks between sections
\setlength{\parindent}{0pt}
\usepackage{array}

\makeatletter

\providecommand{\tabularnewline}{\\}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%% User specified LaTeX commands.
\makeatother
\usepackage{lineno,setspace}
\usepackage{fancyhdr}
\usepackage{lastpage}
\pagestyle{fancy}
\usepackage[small,compact]{titlesec}
\usepackage[small,it]{caption}
\addtolength{\belowcaptionskip}{-3mm}
\addtolength{\abovecaptionskip}{-3mm}
\usepackage{hanging}
\usepackage{babel}
\usepackage{hyperref}
\usepackage{xcolor}
\usepackage{lipsum}
\usepackage{tabularx}
\newcommand\reverselabel[1]{%
  \def\theenumi{}%
  \renewcommand\makelabel{\makebox[\dimexpr\labelwidth-3pt\relax][r]{%
    \the\numexpr#1-\value{enumi}+1\relax}}}%

\makeatother

\fancyhead{}
\renewcommand{\headrulewidth}{0pt}
\fancyfoot{}
\lfoot{Sheth CV}
%\cfoot{CV}
\rfoot{\thepage\ of \pageref{LastPage}}

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

\begin{document}
\SweaveOpts{concordance=TRUE}
\begin {center}

%----------------------------------------------------------------------------------------
%	YOUR NAME AND ADDRESS(ES) SECTION
%----------------------------------------------------------------------------------------

{\huge Seema Nayan Sheth}\tabularnewline
\vspace{1em}

\begin{tabularx}{\textwidth}{@{}>{\raggedright}X >{\raggedleft}X@{}}
\texttt{Seema\_Sheth}@ncsu.edu & Department of Plant and Microbial Biology \tabularnewline
Phone: (919) 515-4168 & North Carolina State University\tabularnewline
\url{www.seemasheth.weebly.com} & Raleigh, NC 27695\tabularnewline
\end{tabularx}
\end{center}
\vspace{-1em}

\rule[0.5ex]{1\linewidth}{0.5pt} 

%----------------------------------------------------------------------------------------
%	PROFESSIONAL APPOINTMENTS
%----------------------------------------------------------------------------------------

\begin{flushleft}
%\vspace{0.5ex}
\section*{PROFESSIONAL APPOINTMENTS}
%\noindent\Large{\textbf{PROFESSIONAL APPOINTMENTS}} 
\vspace{-0.5ex}

{\bf Assistant Professor} \hfill {2018 - present} \newline
Department of Plant and Microbial Biology \newline
North Carolina State University
\vspace{0.5ex}

{\bf National Science Foundation Postdoctoral Fellow} \hfill {2016 - 2017} \newline
Department of Integrative Biology Biology \newline
University of California, Berkeley \newline
Supporting scientists: Dr. David Ackerly and Dr. Bruce Baldwin
\vspace{0.5ex}

{\bf Postdoctoral Research Associate} \hfill {2014 - 2015} \newline
Department of Ecology, Evolution, and Behavior \newline
University of Minnesota \newline
Advisor: Dr. Ruth Shaw
\vspace{0.5ex}

{\bf Research Scientist: Conservation, Ecology, and Evolution} \hfill {2006 - 2008} \newline
Center for Conservation and Sustainable Development \newline
Missouri Botanical Garden

%----------------------------------------------------------------------------------------
%	EDUCATION
%----------------------------------------------------------------------------------------

\vspace{1ex}
\section*{EDUCATION}
%\noindent\Large{\textbf{EDUCATION}} 
\vspace{-0.5ex}

{\bf Ph.D., Ecology} \hfill {2008 - 2014} \newline
Colorado State University \newline
Advisor: Dr. Amy Angert
\vspace{0.5ex}

{\bf M.S., Biology (Ecology, Evolution, and Systematics)} \hfill {2003 - 2006} \newline
University of Missouri - St. Louis \newline
Advisor: Dr. Bette Loiselle
\vspace{0.5ex}

{\bf B.A., Environmental Sciences and Spanish (double major)} \hfill {1998 - 2002} \newline
Washington University in St. Louis
\end{flushleft}

%----------------------------------------------------------------------------------------
%	PUBLICATIONS
%----------------------------------------------------------------------------------------

%\vspace{1ex}
\section*{PUBLICATIONS}
%\noindent\Large{\textbf{PUBLICATIONS}} 
\vspace{-0.5ex}
\begin{hangparas}{.5in}{1}
\begin{enumerate}
\reverselabel{20} %set to total # of publications

\item \textbf{Sheth, S.N.}, N. Morueta-Holme, and A. L. Angert. Determinants of geographic range size in plants. In press, \emph{New Phytologist}. https://doi.org/10.1111/nph.16406.

\item Briscoe Runquist, R. D., A. J. Gorton, J. B. Yoder, N. J. Deacon, J. J. Grossman, S. A. Kothari, M. P. Lyons, \textbf{S. N. Sheth}, P. Tiffin, and D. A. Moeller. 2020. Context dependence of local adaptation to abiotic and biotic environments: a quantitative and qualitative synthesis. In press, \emph{American Naturalist}. https://doi.org/10.1086/707322.

\item Smithers, B. V., M. F. Oldfather, M. J. Koontz, J. Bishop, C. Bishop, J. Nachlinger, and \textbf{S. N. Sheth}. 2020. Community turnover by composition and climate affinity across scales in an alpine system. \emph{American Journal of Botany}. https://doi.org/10.1002/ajb2.1376.

\item Oldfather, M. F., M. M. Kling, \textbf{S. N. Sheth}, N. C. Emery, and D. D. Ackerly. 2020. Range edges in heterogeneous landscapes: integrating geographic scale and climate complexity into range dynamics. \emph{Global Change Biology}. https://doi.org/10.1111/gcb.14897. 

\item Lowry D. B., J. M. Sobel, A. L. Angert, T-L. Ashman, R. L. Baker, B. K. Blackman, Y. Brandvain, K. J. R. P. Byers, A. M. Cooley, J. M. Coughlan, M. R. Dudash, C. B. Fenster, K. G. Ferris, L. Fishman, J. Friedman, D. L. Grossenbacher, L. M. Holeski, C. T. Ivey, K. M. Kay, V. A. Koelling, N. J. Kooyers, C. J. Murren, C. D. Muir, T. C. Nelson, M. L. Peterson, J. R. Puzey, M. C. Rotter, J. R. Seeman, J. P. Sexton, \textbf{S. N. Sheth}, M. A. Streisfeld, A. L. Sweigart, A. D. Twyford, M. Vallejo-Marin, J. H. Willis, C. A. Wu, Y. W. Yuan. 2019. The case for the continued use of the genus name \textit{Mimulus} for all monkeyflowers. \emph{Taxon} 68: 617-623. 

\item Kulbaba, M. W., \textbf{S. N. Sheth}, R. E. Pain, V. M. Eckhart, and R. G. Shaw. 2019. Additive genetic variance for lifetime fitness and the capacity for adaptation in the wild. \emph{Evolution} 73: 1746-1758. 

\item \textbf{Sheth, S. N.}, M. W. Kulbaba, R. E. Pain, and R. G. Shaw. 2018. Expression of additive genetic variance for fitness in a population of partridge pea in two field sites. \emph{Evolution} 72: 2537-2545. 

\item \textbf{Sheth, S. N.} and A. L. Angert. 2018. Demographic compensation does not rescue populations at a trailing range edge. \emph{Proceedings of the National Academy of Sciences (USA)} 115: 2413-2418. 

\item Pain, R. E., R. G. Shaw, and \textbf{S. N. Sheth}. 2018. Costs associated with N-fixing rhizobia early in the life of partridge pea \textit{Chamaecrista fasciculata}. \emph{American Journal of Botany} 105: 796-802. 

\item Morueta-Holme, N., M. F. Oldfather, R. L. Olliff-Yang, A. P. Weitz, C. R. Levine, M. M. Kling, E. C. Riordan, C. Merow, \textbf{S. N. Sheth}, A. H. Thornhill, and D. D. Ackerly. 2018. The language of climate change: best practices in research and publication. \emph{Nature Climate Change} 8: 92-94.

\item Angert, A. L., M. Bayly, \textbf{S. N. Sheth}, and J. R. Paul. 2018. Testing range-limit hypotheses using range-wide habitat suitability and occupancy for the scarlet monkeyflower (\textit{Erythranthe cardinalis}). \emph{American Naturalist} 191: E76-E89.

 \item \textbf{Sheth, S. N.} and A. L. Angert. 2016. Artificial selection reveals high genetic variation in phenology at the trailing edge of a species range. \emph{American Naturalist} 187: 182-193. (American Naturalist 2016 Student Paper Award) 
 
\item \textbf{Sheth, S. N.}, I. Jim\'enez, and A. L. Angert. 2014. Identifying the paths leading to variation in geographical range size in western North American monkeyflowers. \emph{Journal of Biogeography} 41: 2344-2356. 

\item \textbf{Sheth, S. N.} and A. L. Angert. 2014. The evolution of environmental tolerance and range size: a comparison of geographically restricted and widespread \textit{Mimulus}. \emph{Evolution} 68: 2917-2931. 

\item \textbf{Sheth, S. N.}, L. G. Lohmann, T. Distler, and I. Jim\'enez. 2012. Understanding bias in geographic range size estimates. \emph{Global Ecology and Biogeography} 21: 732-742.
 
 \item Paul, J. R., \textbf{S. N. Sheth}, and A. L. Angert. 2011. Quantifying the impact of gene flow on phenotype-environment mismatch: a demonstration with the scarlet monkeyflower \textit{Mimulus cardinalis}. \emph{American Naturalist} 178: S62-S79. 
 
\item Angert, A. L., \textbf{S. N. Sheth}, and J. R. Paul. 2011. Incorporating population-level variation in thermal performance into predictions of geographic range shifts. \emph{Integrative And Comparative Biology} 51: 733-750. 

\item \textbf{Sheth, S. N.}, B. A. Loiselle, and J. G. Blake. 2009. Phylogenetic constraints on fine-scale patterns of habitat use by eight primate species in eastern Ecuador. \emph{Journal of Tropical Ecology} 25: 571-582. 

\item \textbf{Sheth, S. N.}, L. G. Lohmann, T. Consiglio, and I. Jim\'enez. 2008. Effects of detectability on estimates of geographic range size in Bignonieae. \emph{Conservation Biology} 22: 200-211. 

\item Amend, J. P., D. A. R. Meyer-Dombard, \textbf{S. N. Sheth}, N. Zolotova, and A. C. Amend. 2003. \textit{Palaeococcus helgesonii} sp. nov., a facultatively anaerobic, hyperthermophilic archaeon from a geothermal well on Vulcano Island, Italy. \emph{Archives of Microbiology} 179: 394-401. 
\end{enumerate}
\end{hangparas}

%\subsection*{\textit{In review} or \textit{In revision}}
%\begin{hangparas}{.5in}{1}

%Wooliver, R., S.B. Tittes, \textbf{S.N. Sheth}. A resurrection study reveals rapid evolution of thermal performance in a leading range edge population in response to recent climate change. In review, \emph{Ecology Letters}.

%\end{hangparas}

%----------------------------------------------------------------------------------------
%	GRANTS, FELLOWSHIPS, AND AWARDS
%----------------------------------------------------------------------------------------
%\vspace{2ex}
%\begin{flushleft}
\section*{GRANTS, FELLOWSHIPS, AND AWARDS}
%\noindent\Large{\textbf{GRANTS, FELLOWSHIPS, AND AWARDS}} 
%\end{flushleft}
\vspace{-0.5ex}

\renewcommand{\arraystretch}{1.2}
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}
NCSU Faculty Research and Professional Development Fund, \$5,000 & 2019 - 2020 \tabularnewline
\addtolength{\leftskip}{5ex}\emph{Rapid evolution of thermal tolerance across a species' geographic range} (PI)  & \tabularnewline

American Naturalist 2016 Student Paper Award & 2017 \tabularnewline

NSF Postdoctoral Research Fellowship in Biology, \$138,000 & 2016 - 2017 \tabularnewline
\addtolength{\leftskip}{5ex}\emph{Relationships among climatic tolerance, trait evolution, and diversification in the California flora} \tabularnewline

Postdoctoral Association Career Development Award, Univ. of Minnesota, \$400 & 2015 \tabularnewline 

Finalist, University of California President's Postdoctoral Fellowship & 2014
\tabularnewline

NSF DEB Evolutionary Ecology, \$14,984 & 2012 - 2014 \tabularnewline
\addtolength{\leftskip}{5ex}\emph{Dissertation Research: Role of evolutionary potential in limiting distributions} (co-PI)
\vspace{0.5ex} \tabularnewline

\end{tabularx}

\renewcommand{\arraystretch}{1.2}
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}

Outreach Grant, Society for the Study of Evolution, \$800 & 2012 \tabularnewline

Global Sustainability Leadership Fellow, Colorado State University & 2012 \tabularnewline

Rosemary Grant Award, Society for the Study of Evolution, \$2,500 & 2010 \tabularnewline

Graduate Student Research Award, Botanical Society of America, \$500 & 2010
\tabularnewline

Finalist, Environmental Protection Agency STAR Graduate Fellowship & 2009
\tabularnewline

Steinkamp Fund, Colorado Native Plant Society, \$1,000 & 2009
\tabularnewline

Women in Natural Sciences Travel Grant, Colorado State University, \$300 & 2009\tabularnewline

Awards from Department of Biology, Colorado State University, \$7,425 & 2009 - 2014\tabularnewline

Grad. Degree Program in Ecology Fellowship, Colorado State University, \$1,000 & 2008 \tabularnewline

NSF GK-12 Fellowship, Colorado State University, \$4,000 & 2008 \tabularnewline

NSF GK-12 Fellowship, Univ. of Missouri-St. Louis, \$30,000 & 2005 - 2006\tabularnewline

Awards from Department of Biology, Univ. of Missouri-St. Louis, \$3,500 & 2004 - 2005\tabularnewline

Primate Action Fund, Conservation International, \$3,000 & 2004\tabularnewline

\end{tabularx}

\vspace{0.5ex}

%----------------------------------------------------------------------------------------
%	ADD PAGE BREAK; MOVE MANUALLY IF NEEDED
%----------------------------------------------------------------------------------------
%\newpage

%----------------------------------------------------------------------------------------
%	PRESENTATIONS
%----------------------------------------------------------------------------------------
%\vspace{1.5ex}
%\begin{flushleft}
\section*{PRESENTATIONS}
\vspace{-0.5ex}
\subsection*{Invited symposia}
%\nopagebreak[0]
%\end{flushleft}

\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in}
>{\raggedleft}X@{}}
International Biogeography Society Humboldt-250 Meeting, Quito, Ecuador & 2019 \tabularnewline
\addtolength{\leftskip}{5ex} Symposium: Architects of variation: How climate and physiology shape patterns of biodiversity  \tabularnewline
\addtolength{\leftskip}{5ex} ``Can plant thermal tolerance evolve under climate change? A comparison of central and edge populations'' (R. Wooliver, S. Tittes, and \textbf{S.N. Sheth}; presented by R. Wooliver)
\tabularnewline

Green Life Sciences, University of Michigan, Ann Arbor, MI & 2018 \tabularnewline
\addtolength{\leftskip}{5ex} Symposium: Plant-environment interactions across scales  \tabularnewline
\addtolength{\leftskip}{5ex} ``Do demographic compensation and adaptation buffer species from changing climate?'' \tabularnewline

Society for the Study of Evolution, Portland, OR & 2017 \tabularnewline
\addtolength{\leftskip}{5ex} American Society of Naturalists Symposium: Across the Nth dimension: Quantitative and conceptual advances in the study of niche breadth  \tabularnewline
\addtolength{\leftskip}{5ex} ``Does niche breadth predict vulnerability to changing environments? From population-level traits and demography to diversification in deep time'' \tabularnewline

SACNAS, Long Beach, CA & 2016 \tabularnewline
\addtolength{\leftskip}{5ex} Scientific Symposium: (Day and) Night at the Museum: Exploring Research in Ecology and Evolution Behind the Scenes of Natural History Museums \tabularnewline
\addtolength{\leftskip}{5ex} ``Harnessing the power of herbarium specimen data for ecological and evolutionary studies'' \tabularnewline

Jornadas Argentinas de Botanica, Corrientes, Argentina & 2007 \tabularnewline
\addtolength{\leftskip}{5ex} Symposium: Conservation and Threat Assessments of Plants \tabularnewline
\addtolength{\leftskip}{5ex} ``Riesgo de extinci\'on en Bignonieae (Bignoniaceae): una perspectiva filogen\'etica'' (\textbf{Sheth, S.N.}, L.G. Lohmann, T. Consiglio, and I. Jim\'enez) \tabularnewline

\end{tabularx}

\renewcommand{\arraystretch}{1.2}
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}

Botanical Society of America and Plant Biology Joint Congress, Chicago, IL & 2007 \tabularnewline
\addtolength{\leftskip}{5ex} Colloquium: Integration of spatial and ecological data in evolutionary studies \tabularnewline
\addtolength{\leftskip}{5ex} ``Extinction risk in Bignonieae (Bignoniaceae): a phylogenetic perspective'' (\textbf{Sheth, S.N.}, L.G. Lohmann, T. Consiglio, and I. Jim\'enez) \tabularnewline

\end{tabularx}
\vspace{-0.5ex}

%\begin{flushleft}
\subsection*{Invited seminars}
%\end{flushleft}
%\vspace{-1ex}

Department of Integrative Biology, University of California, Berkeley (upcoming) \hfill{2020}
Department of Ecology and Evolutionary Biology, University of Arizona (upcoming) \hfill{2020}
Department of Ecology and Evolutionary Biology, Michigan State University (upcoming) \hfill {2020} \newline
Department of Ecology and Evolutionary Biology, University of Colorado (upcoming) \hfill {2020} \newline
Department of Ecology and Evolutionary Biology, Tulane University \hfill {2019} \newline
Program in Ecology, Duke University \hfill {2019}\newline
Kellogg Biological Station, Michigan State University \hfill {2019} \newline
Genetics and Genomics Seminar Series, North Carolina State University \hfill {2019} \newline
Bio-Pop Seminar Series, Department of Biology, University of North Carolina \hfill {2018} \newline
Department of Plant Biology, University of Vermont \hfill {2018} \newline
EEBio Seminar Series, Department of Biology, University of Virginia \hfill {2018} \newline
Department of Forestry and Environmental Resources, North Carolina State University \hfill {2018} \newline
Department of Biological Sciences, California Polytechnic State University \hfill {2017} \newline
Department of Ecology and Evolutionary Biology, University of California, Los Angeles \hfill {2017} \newline
Environmental Systems Graduate Group, University of California, Merced \hfill {2017} \newline
School of Integrative Plant Science, Plant Biology Section, Cornell University \hfill {2017} \newline
Center for Population Biology, University of California, Davis \hfill {2017} \newline
Department of Biology, University of Utah \hfill {2017} \newline
Natural History Museum of Utah \hfill {2017} \newline
Department of Plant and Microbial Biology, North Carolina State University \hfill {2017} \newline
Department of Biology, Williams College \hfill {2016} \newline
Department of Biology, University of San Francisco \hfill {2016} \newline
Department of Biology, Grinnell College \hfill {2015} \newline
Department of Plant Biology, University of Minnesota \hfill {2015} \newline
Department of Biology, Washington University in St. Louis \hfill {2007} \newline
Department of Biology, St. Louis University \hfill {2007} \newline
\vspace{-2ex}

\begin{samepage}

%\begin{flushleft}
\subsection*{Contributed conference presentations} \Needspace{2in} %needspace moves section heading to previous page
%\end{flushleft}

\renewcommand{\arraystretch}{1.2}
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}

\hangindent=5ex \ Kulbaba, M., \textbf{S.N. Sheth}, R.E. Pain, V.M. Eckhart, and R.G. Shaw. ``Adaptive potential and realized changes in fitness in natural populations.'' Society for the Study of Evolution, Montpellier, France (poster) & 2018 \tabularnewline

\hangindent=5ex \ \textbf{Sheth, S.N.} and A.L. Angert. ``Demographic compensation does not rescue \textit{Erythranthe cardinalis} populations at the southern edge of the species range.'' Ecological Society of America, Portland, OR & 2017 \tabularnewline

\hangindent=5ex \ Kulbaba, M., R.E. Pain, V.M. Eckhart, \textbf{S.N. Sheth}, and R.G. Shaw. ``The immediate capacity for adaptation and its realization in natural plant populations.'' International Botanical Congress, Shenzhen, China & 2017 \tabularnewline

\hangindent=5ex \ \textbf{Sheth, S.N.}, M. Kulbaba, R.E. Pain, and R.G. Shaw. ``Expression of additive genetic variance for fitness in a population of partridge pea grown in two field sites.'' Society for the Study of Evolution, Portland, OR (presented by R.G. Shaw) & 2017 \tabularnewline

\hangindent=5ex \ \textbf{Sheth, S.N.}, W.A. Freyman, B.G. Baldwin, and D.D. Ackerly. ``Relationships among rates of climatic niche evolution and diversification.'' Society for the Study of Evolution, Austin, TX (poster) & 2016 \tabularnewline

\hangindent=5ex \ \textbf{Sheth, S.N.} and A.L. Angert. ``Artificial selection reveals high genetic variation in phenology at the trailing edge of a species range.'' Ecological Society of America, Baltimore, MD & 2015 \tabularnewline

\hangindent=5ex \ \textbf{Sheth, S.N.} and A.L. Angert. ``Does a jack-of-all-temperatures have a large geographic range?'' Society for the Study of Evolution, Snowbird, UT & 2013 \tabularnewline

\hangindent=5ex \ \textbf{Sheth, S.N.}, I. Jim\'enez, and A.L. Angert. ``Effects of niche properties on variation in geographic range size among species of western North American monkeyflowers.'' Ecological Society of America, Portland, OR & 2012 \tabularnewline

\hangindent=5ex \ \textbf{Sheth, S.N.}, L.G. Lohmann, T. Distler, and I. Jim\'enez. ``The Wallacean shortfall: bias in estimates of geographic range size.'' Botanical Society of America, St. Louis, MO (presented by I. Jim\'enez) & 2011 \tabularnewline

\hangindent=5ex \ \textbf{Sheth, S.N.} and A.L. Angert. ``Ecological niche attributes and geographic range size in western North American monkeyflowers.'' Society for the Study of Evolution, Portland, OR & 2010 \tabularnewline

% NOTE: THIS CHUNK SHOULD BE MANUALLY MOVED SO THAT PAGE BREAK IS CORRECT
\end{tabularx}
\end{samepage}

\renewcommand{\arraystretch}{1.2} 
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}
% END NOTE

\hangindent=5ex \ \textbf{Sheth, S.N.}, L.G. Lohmann, I. Jim\'enez, and T. Consiglio. ``Riesgo de extinci\'on en Bignonieae (Bignoniaceae) estimado con datos de herbario." Congreso Latinoamericano de Bot\'anica. Santo Domingo, Dominican Republic (presented by L. G. Lohmann) & 2006 \tabularnewline 

\end{tabularx}

%----------------------------------------------------------------------------------------
%	TEACHING
%----------------------------------------------------------------------------------------
%\vspace{1.5ex}
%\begin{flushleft}
\section*{TEACHING}

\subsection*{North Carolina State University}
%\end{flushleft}
Plant Ecology, PB495/595-003, solo instructor \hfill {2019 - present} 


%\begin{flushleft}
\subsection*{Colorado State University}
%\end{flushleft}
Principles of Plant Biology Laboratory, teaching assistant \hfill {2008 - 2014} \newline
Plant Ecology, guest lecturer \hfill {2012 - 2013} \newline
Plant Ecology, teaching assistant \hfill {2011 - 2012} \newline
Biology of Organisms, guest lecturer \hfill {2009} \newline
Cache La Poudre Junior High School, NSF GK-12 fellow, LaPorte, CO \hfill {2008 - 2009}

%\begin{flushleft}
\subsection*{Missouri Botanical Garden}
%\end{flushleft}
Neotropical Plant Families, guest lecturer for University of Michigan course \hfill {2008} \newline
Conservation Biology, guest lecturer for University of Missouri - St. Louis course \hfill {2008} 

%\begin{flushleft}
\subsection*{University of Missouri - St. Louis}
%\end{flushleft}
McCluer High School, NSF GK-12 fellow, Florissant, MO \hfill {2005 - 2006} \newline
Organisms and th Environment Laboratory, guest lecturer \hfill {2005} 

%\begin{flushleft}
\subsection*{AmeriCorps Partnership for Youth}
%\end{flushleft}
Woodward Elementary School, tutor and teaching assistant, St. Louis, MO \hfill {2002 - 2003} 

%----------------------------------------------------------------------------------------
%	MENTORING
%----------------------------------------------------------------------------------------
\section*{MENTORING}

%\renewcommand{\arraystretch}{1.2}
%\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}

\subsection*{North Carolina State University}
\subsubsection*{\emph{Postdoctoral associates}}
Dr. Rachel Wooliver \hfill {2018 - present}
\subsubsection*{\emph{Graduate students}}
Aleah Querns (M.S.) \hfill {2018 - present} \newline
Emma Vtipil (M.R.) \hfill {2019 - present}

\subsubsection*{\emph{Undergraduate researchers}}
Brooke Caldwell \hfill {2019 - present} \newline
Natalie Gold \hfill {2019} \newline
Mariah Kidd \hfill {2019 - present} \newline
Daisy Ryan \hfill {2020 - present} \newline 
Jessie Torres \hfill {2018 - 2019} \newline
Emma Vtipil (Honor's thesis student; recipient of NCSU Chilton Research Award) \hfill {2018 - 2019} \newline
Mia Wiegmann \hfill {2018 - present} \newline 
Collin Yurish \hfill {2018 - 2019} 

\subsubsection*{\emph{Graduate student committees}}
Samuel Flake \hfill {2018 - present} \newline
Simon Pinilla-Gallego \hfill {2018 - present} \newline
Greg Wilson \hfill {2018 - 2019} 

\subsection*{University of California, Berkeley}
\hangindent=5ex Mentored 7th graders at King Middle School as part of Be a Scientist outreach program \hfill {2017} 

\subsection*{University of Minnesota}
Sam Weaver (NSF REU student from St. Olaf College)		 \hfill {2015} 

\subsection*{Colorado State University}
Amber Weimer (Honor's thesis undergraduate student)		 \hfill {2013 - 2014} \newline
Trained, mentored, and supervised 17 undergraduates \& recent college graduates		 \hfill {2009 - 2014} \newline
Biological Summer Undergraduate Research Experience program committee member \hfill {2012} 

%----------------------------------------------------------------------------------------
%	SERVICE
%----------------------------------------------------------------------------------------
\vspace{1.5ex}
%\begin{flushleft}
\section*{SERVICE}
\vspace{-0.5ex}
%\end{flushleft}
%\begin{flushleft}
\subsection*{University service}

Ecology faculty search committee, Dept. of Plant and Microbial Biology, NCSU \hfill{2019 - 2020 }\newline
College of Agricultural and Life Sciences greenhouse committee, NCSU \hfill{2019 - present}\newline
Plant Biology Graduate admissions committee, NCSU \hfill{2018 - present} \newline 
Biology faculty search committee, Colorado State University \hfill{2012 - 2013} 

\subsection*{Professional service}
\renewcommand{\arraystretch}{1.2}
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}
\hangindent=5ex Manuscript reviewer: \emph{American Journal of Botany, American Naturalist, Annals of Botany, AoB PLANTS, BMC Evolutionary Biology, Ecography, Ecological Applications, Ecology, Ecology Letters, Evolution, Evolutionary Ecology, Functional Ecology, Journal of Animal Ecology, Journal of Ecology, Molecular Ecology, New Phytologist, Science Advances} & 2009 - present \tabularnewline
\hangindent=5ex Hamilton student award committee member, Society for the Study of Evolution & 2020 - present \tabularnewline
Book proposal reviewer: Oxford University Press & 2018 \tabularnewline                               
Proposal reviewer: NSF DEB, Population and Community Ecology & 2014 
\end{tabularx}

\subsection*{Other service}
\renewcommand{\arraystretch}{1.2}
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}
\hangindent=5ex Volunteer: Global Observation Research Initiative in Alpine Environments (GLORIA), White Mountains Wilderness, California & 2017 - present \tabularnewline
\hangindent=5ex Exhibitor, Darwin Day, North Carolina Museum of Natural Sciences & 2019 \tabularnewline
\hangindent=5ex Advisory board member: Science Ambassador Scholarship (for undergraduate women in science, technology, engineering, or math), Cards Against Humanity & 2017 - 2018 \tabularnewline
\hangindent=5ex Collaborated with National Park Service to recruit Navajo Nation students to assist with fieldwork in Canyon de Chelly National Monument, AZ & 2009 \tabularnewline			
Volunteer, Putnam Elementary Science Carnival, Fort Collins, CO & 2009 \tabularnewline                                
Volunteer, Unidad T\'ecnica (environmental NGO), Managua, Nicaragua &2001 \\*[0.7em]
%\end{flushleft}
\end{tabularx}
 
%----------------------------------------------------------------------------------------
%	ADD PAGE BREAK; MOVE MANUALLY IF NEEDED
%----------------------------------------------------------------------------------------
\newpage

%----------------------------------------------------------------------------------------
%	WORKING GROUPS AND WORKSHOPS
%----------------------------------------------------------------------------------------
%\vspace{1.5ex}
%\begin{flushleft}
\vspace{-2ex}
\begin{samepage}
\section*{WORKING GROUPS AND WORKSHOPS} \Needspace{2in} %needspace moves section heading to previous page
\vspace{-0.5ex}

\renewcommand{\arraystretch}{1.2} 
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}

\hangindent=5ex Agricultural Leadership Learning Institute for Faculty, North Carolina State University, Raleigh, NC & 2019 \tabularnewline 

\hangindent=5ex Evolution in Changing Seas Synthesis Workshop, Shoals Marine Laboratory, Appledore, ME & 2019 \tabularnewline  

\hangindent=5ex Software Carpentry Workshop, Berkeley Institute of Data Sciences, Berkeley, CA & 2016 \tabularnewline

\hangindent=5ex Early Career Centennial Mentoring Program, Ecological Society of America, Baltimore, MD & 2015 \tabularnewline

\hangindent=5ex Quantitative Genetics and Mixed Models in Quantitative Genetics, Summer Institute in Statistical Genetics, University of Washington, Seattle, WA & 2013 \tabularnewline    

\hangindent=5ex Intro to Python for ArcGIS Workshop, Colorado State University, Fort Collins, CO & 2016 \tabularnewline

\hangindent=5ex Science Communication Workshop, Colorado State University, Fort Collins, CO	& 2012 \tabularnewline


\hangindent=5ex Living on the edge: integrating science into the management of range-margin populations, University of Wyoming, Laramie, WY & 2010 \tabularnewline			

\hangindent=5ex Applied Phylogenetics Workshop, Bodega Bay Marine Laboratory, CA & 2010 \tabularnewline

\hangindent=5ex Working with ArcGIS Spatial Analyst (short course), Environmental Systems Research Institute, St. Charles, MO & 2007 \tabularnewline

\hangindent=5ex Distance Sampling Workshop, University of Missouri - St. Louis, St. Louis, MO & 2006 \tabularnewline

\hangindent=5ex Assessing extinction risk in Bignonieae (summer internship), Center for Conservation and Sustainable Development, Missouri Botanical Garden, St. Louis, MO & 2005 \tabularnewline

% NOTE: THIS CHUNK SHOULD BE MANUALLY MOVED SO THAT PAGE BREAK IS CORRECT
\end{tabularx}
\end{samepage}

\renewcommand{\arraystretch}{1.2} 
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}
% END NOTE

\hangindent=5ex Geographic Information Systems (course), University of Missouri - St. Louis & 2004 \tabularnewline

\hangindent=5ex Tropical Biology: An Ecological Approach (course), Organization for Tropical Studies, Costa Rica & 2004 \tabularnewline

\hangindent=5ex Historical Biogeography (short course), University of Missouri - St. Louis & 2004 \tabularnewline

\end{tabularx}

%\end{flushleft}

%----------------------------------------------------------------------------------------
%	PROFESSIONAL AFFILIATIONS AND SOCIETIES
%----------------------------------------------------------------------------------------
%\vspace{1.5ex}
%\begin{flushleft}
%\vspace{-2ex}
\section*{PROFESSIONAL AFFILIATIONS AND SOCIETIES}
%\vspace{-0.5ex}
%\end{flushleft}

\renewcommand{\arraystretch}{1.2}
\begin{tabularx}{\textwidth}{@{}>{\raggedright}p{5.25in} >{\raggedleft}X@{}}

\hangindent=5ex Science Director: GLORIA (Global Observation Research Initiative in Alpine Environments) Great Basin \tabularnewline
Faculty Affiliate: Southeast Climate Science Center \tabularnewline
American Society of Naturalists \tabularnewline
Botanical Society of America \tabularnewline
Ecological Society of America \tabularnewline
Society for the Study of Evolution \tabularnewline
\end{tabularx}
\vfill
\begin{center}
\textit{last updated \today}
\end{center}
\end{document}